###
SCENE:   assemble
MMP_CFG: ald_1t20_train.yml
MPC_CFG: mpc_default.yaml

STIME:   0.2 # seconds
PRED_OFFSET: 20

SIM_WIDTH:  64
SIM_HEIGHT: 40

SCALE2NN:   10   # rescale to the neural network coords
SCALE2REAL: 1 # rescale to the real-world coords

IMAGE_AXIS: False # use image axis or Cartesian axis
CORNER_COORDS: # offset in real world, if the corner is not (0,0)
  - 0
  - 0



